### ISSUE TITLE
Use jinja conditions for deduplicating nginx conf?

### ISSUE THREAD

**Issue by fflorent** [chadek/ansible-role-nginx-certbot#2]
Jinja supports conditions:
 - plain if: https://jinja.palletsprojects.com/en/3.0.x/templates/#if
 - inline: https://jinja.palletsprojects.com/en/3.0.x/templates/#if-expression

What do you think of using that like this way to merge both `templates/nginx_reverse_proxy.j2` and `templates/nginx_reverse_proxy_log.j2` into a single file?

```jinja
{% if logging %}
log_format proxy_https '$proxy_protocol_addr - $remote_user [$time_local] '
                       '"$request" $status $body_bytes_sent '
                       '"$http_referer" "$http_user_agent"';

{% endif %}

 ### HTTPS server
 server {
 
 
   # SSL configuration
   listen [::]:443 ssl http2 {% 'proxy_protocol' if logging %};
   include snippets/ssl-params.conf;
   ssl_certificate /etc/letsencrypt/live/{{ nginx_certbot_domain_name }}/fullchain.pem;
   ssl_certificate_key /etc/letsencrypt/live/{{ nginx_certbot_domain_name }}/privkey.pem;
@@ -52,4 +56,5 @@
   error_log   /var/log/nginx/{{ nginx_certbot_app.name }}_error.log;
 
   include /etc/nginx/conf.d/{{ nginx_certbot_domain_name }}.d/*.conf;
 }
```

Pros:
 - avoid duplicating files and thus maintaining the two;
 - have a clear understanding of the differences between enabling the logs or not in the configuration;

Cons:
 - more syntax so more complex and maybe there is a cost in term of readability;

**Comment by chadek** [comment]
[This pr](https://github.com/chadek/ansible-role-nginx-certbot/pull/5) should fix it! Better late than never
